### ISSUE TITLE
Customize Account Details

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-workflows#24]
#### Describe the desired behavior
End users should be able to specify what details they want to capture on the account details screen of registration. The should be able to specify which fields are required, custom validation for fields, etc.

#### Describe the current behavior
Only three hardcoded fields (first, last, phone).

#### Is this request related to a current issue?
No

**Comment by joebochill** [comment]
This will likely be something we need to do as part of our realignment with the work that shiverware has done on their implementation of the workflow.

**Comment by jeffvg** [comment]
moved to PXBLUE-1928
