### ISSUE TITLE
Upgrade to RNP 4

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-workflows#29]
#### Describe the desired behavior
Use the latest 4.x version of React Native Paper

#### Describe the current behavior
Using 3.x

#### Is this request related to a current issue?
No

#### Additional Context
We can go in and clean up a bunch of ts-ignore comments and/or unnecessary 'accessibilityStates' props now.

**Comment by huayunh** [comment]
TODO: 
- Create a backlog item for this (like what we did for ng 10)
- and clean up CLI?

**Comment by huayunh** [comment]
Logged an new issue to the too groom queue PXBLUE-1659
