### ISSUE TITLE
Android example app EULA agreement cut off

### ISSUE THREAD

**Issue by dwshiver** [pxblue/react-native-workflows#37]
When running the example app on Android (Pixel 4 emulator API 29, Android Studio 4.1.1), the "I have read and agree to the Terms & Conditions" text gets cut off on the right side. I think this also existed prior to 2.x.

<img width="487" alt="Screen Shot 2020-12-11 at 12 26 29 PM" src="https://user-images.githubusercontent.com/26386179/101941733-04742180-3bae-11eb-925f-e80431661dde.png">

**Comment by huayunh** [comment]
For the convenience of yinz developers, here is a 200% ratio screenshot from WAS's figma file:
![image](https://user-images.githubusercontent.com/8997218/101969721-f648f400-3bf3-11eb-848b-a9f11b86a531.png)

**Comment by daileytj** [comment]
https://react-native.canny.io/feature-requests/p/flexdirection-row-breaks-wrap-and-forces-content-off-screen

**Comment by jeffvg** [comment]
This text should wrap to be viewable.
