### ISSUE TITLE
AsyncStorage has moved

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-workflows#44]
#### Describe the bug
When installing dependencies there is a warning that says that AsyncStorage has moved to a new location.

#### What is the expected behavior?
No warnings, use the newer package location.

#### What are the steps to reproduce?
1. Clone the repo
2. Start the demo
3. Observe the terminal output

#### Anything else to add?
This should be as simple as swapping out the package in the dependencies and updating the import statement.

**Comment by emclaug2** [comment]
Check & make sure we don't need to change anything in the integration docs.  README, etc.

**Comment by emclaug2** [comment]
It's in the install & setup into existing project section.
