### ISSUE TITLE
example projects forgot password screen email field not viewable

### ISSUE THREAD

**Issue by jeffvg** [pxblue/react-native-workflows#84]
#### Describe the bug
while running through the forgot password workflow, the email address field is not in view and covered by keyboard. Unable to scroll in to view
#### What is the expected behavior?
email field not covered by keyboard
#### What are the steps to reproduce?
1. Go to debug
2. Click on forgot password
3. Click/touch in email field
4. keyboard covers field and not able to scroll in to view. (unable to view what's typed in field)

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/123673218-3711fe80-d80e-11eb-918f-efeca569e4d4.png)

**Comment by joebochill** [comment]
We should check to see if this is an issue in a new project from the CLI and also whether it is an Android-specific issue or if it affects iOS too.

**Comment by jeffvg** [comment]
verified this with new react native auth template from pxb cli...

Android keyboard pushes reset password button up and overlays the email address field and blocks what user is typing.

![image](https://user-images.githubusercontent.com/37150565/124929319-683cbc80-dfce-11eb-8f08-d46cae279029.png)
iOS keyboard does not push the reset password button up and email address field is in view

![image](https://user-images.githubusercontent.com/37150565/124941620-ee5e0080-dfd8-11eb-907a-fbc36880c7d1.png)
