### ISSUE TITLE
Empty EULA Screen when htmlEula is set to true

### ISSUE THREAD

**Issue by dwshiver** [pxblue/react-native-workflows#86]
#### Describe the bug

In the example app when trying to load HTML for the EULA, the EULA screen remains empty in both the self registration pager and the invite pagers.

#### What is the expected behavior?

The EULA screen should handle HTML when htmlEula is set to true.

#### What are the steps to reproduce?
1. Open `App.tsx` in the example project and set `htmlEula` to `{true}` on the `AuthUIContextProvider` in `AuthUIConfiguration`.
2. Open `RegistrationUIActions.tsx` in `example/src/actions` and modify the `loadEULA` function to return valid HTML. Here is a simple minified HTML string to use: `<!DOCTYPE html><html lang="en"><head><title>A simple HTML document</title></head><body><p>Hello World!<p></body></html>`
3. Run the app and go through the self registration flow.
4. When you arrive at the EULA screen, the HTML EULA won't load.

#### Screenshots or links to minimum reproduction example
<img width="497" alt="Screen Shot 2021-07-06 at 4 17 23 PM" src="https://user-images.githubusercontent.com/26386179/124784567-49bdbf00-df03-11eb-81be-cf0a9086008e.png">

#### Environment
This occurs on both Android and iOS. Tested on Xcode 12 on an iOS 14.5 simulator (iPhone 12). Tested on Android Studio 4.2.1 on an API level 30 emulator (Pixel 4a).

**Comment by joebochill** [comment]
This may be an issue with the react-native-webviews version....will look into this.

**Comment by joebochill** [comment]
@dwshiver Looks like this is just a flex issue that slipped in when we made some responsive styling changes (it's hiding up at the top with no height)...should have a patch out for this very soon.
