### ISSUE TITLE
Reset Password Close Icon in Wrong Spot on iOS 15

### ISSUE THREAD

**Issue by dshiverware** [pxblue/react-native-workflows#97]
#### Describe the bug

On iOS 15 in a iPhone 12 simulator, the 'X' close button on the Reset Password screen is higher than it should be. This doesn't appear to happen on any of the other screens.

#### What is the expected behavior?

The close button should be in the correct position.

#### What are the steps to reproduce?
1. Go to the login screen
2. Click on the "Debug" button
3. Click on "Test Reset Password"
4. The close button will be in the wrong spot.

#### Screenshots or links to minimum reproduction example

<img width="564" alt="Screen Shot 2021-10-19 at 9 48 40 AM" src="https://user-images.githubusercontent.com/26386179/137946764-48e4ee20-f1fd-4e6d-9e1d-87be66d48e7e.png">

#### Environment

iPhone 12 simulator running iOS 15 on Xcode 13.0.

**Comment by joebochill** [comment]
Version 3->4 should be mostly the same, just a major version update due to the change in peer dependencies to @pxblue/react-native-components >= 6

**Comment by dshiverware** [comment]
Yes, updating the auth workflow to 4.0.0-beta.0 seems to fix this in our app. Thanks!

**Comment by emclaug2** [comment]
Closing this issue
